version: 0.2

phases:
  build:
    commands:
      - ./gradlew assembleDebug
      - pwd
      - ls
      - cd app/build/outputs/
      - ls
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - app/build/outputs/apk/app-debug.apk
